import { buildClient } from "../../../api/build-client";
import Layout from "../../../components/layouts";

const privacyPolicy = ({ privacyPolicy }) => {
  return (
    <Layout
      smallLeaderboard
      leaderboardData={{ header: "Privacy Policy", subHeader: "" }}
    >
      <p class="p3">
        10goTech is committed to protecting your privacy. It governs the Privacy
        Terms of our Platform, located at https://www.10gotech.com This Privacy
        Policy explains how your personal information is collected, used, and
        disclosed by our Company.
      </p>
      <p class="p3">
        By accessing or using our Service, you announce that you have read,
        understood, and agree to our collection, storage, use, and disclosure of
        your personal information as described in this Privacy Policy and our
        Terms of Service.<span class="Apple-converted-space">&nbsp;</span>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p5">
        <strong>Definitions</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <ul class="ul1">
        <li class="li6">
          <span class="s2">
            <strong>Personal Data:</strong> Personal Data means data about a
            living individual who can be identified from those data. Personal
            Data is any information that directly, indirectly, or in connection
            with other information allows for the identification of a natural
            person.<span class="Apple-converted-space">&nbsp;</span>
          </span>
        </li>
        <li class="li6">
          <span class="s2">
            <strong>Usage Data:</strong> Usage Data is data collected
            automatically either generated by the use of the Service or from the
            Service infrastructure itself (for example, the duration of a page
            visit).
          </span>
        </li>
        <li class="li7">
          <span class="s3">
            <strong>Cookies:</strong>&nbsp;
          </span>
          <span class="s2">
            Small amount of data generated by a website and saved by your web
            browser. It is used to identify your browser, provide analytics,
            remember information about you such as your language preference or
            login information.
          </span>
        </li>
        <li class="li6">
          <span class="s2">
            <strong>Data Controller:</strong> Data Controller means a natural or
            legal person who (either alone or jointly or in common with other
            persons) determines the purposes for which and the manner in which
            any personal data are, or are to be processed. For the purpose of
            this Privacy Policy, we are a Data Controller of your data.
          </span>
        </li>
        <li class="li6">
          <span class="s2">
            <strong>Data Processors (or Service Providers):</strong> Data
            Processor (or Service Provider) means any natural or legal person
            who processes the data on behalf of the Data Controller. We may use
            the services of Service Providers in order to process your data more
            effectively.
          </span>
        </li>
        <li class="li7">
          <span class="s2">
            <strong>Third-party service</strong>:&nbsp;refers to advertisers,
            contest sponsors, promotional and marketing partners, and others who
            provide our content or whose products or services we think may
            interest you.
          </span>
        </li>
        <li class="li6">
          <span class="s2">
            <strong>Data Subject:</strong> Data Subject is any living individual
            who is the subject of Personal Data.
          </span>
        </li>
        <li class="li6">
          <span class="s2">
            <strong>User:</strong> The User is the individual using our Service.
            The User corresponds to the Data Subject, who is the subject of
            Personal Data.
          </span>
        </li>
      </ul>
      <p class="p4">
        <br />
      </p>
      <p class="p5">
        <strong>What Information Do We Collect?</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p8">
        We collect several types of information for various purposes to provide
        and improve our Service to you.
      </p>
      <p class="p9">
        <br />
      </p>
      <p class="p10">
        <strong>Types of Data Collected</strong>
      </p>
      <p class="p9">
        <br />
      </p>
      <ul class="ul1">
        <li class="li11">
          <span class="s2">
            <strong>Personal Data</strong>
          </span>
        </li>
      </ul>
      <p class="p8">
        While using our Service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you (Personal Data). It means - Email address, first and last
        name, address, Country, Postcode, Phone number.
      </p>
      <p class="p12">
        <br />
      </p>
      <ul class="ul1">
        <li class="li11">
          <span class="s2">
            <strong>Usage Data</strong>
          </span>
        </li>
      </ul>
      <p class="p12">
        <br />
      </p>
      <p class="p8">
        We may also collect information on how the Service is accessed and used
        (Usage Data). This Usage Data may include information such as your
        computer&apos;s Internet Protocol address (IP address), browser type,
        browser version, the pages of our Service that you visit, the time and
        date of your visit, the time spent on those pages, unique device
        identifiers and other diagnostic data.
      </p>
      <p class="p12">
        <br />
      </p>
      <ul class="ul1">
        <li class="li6">
          <span class="s2">
            <strong>Tracking &amp; Cookies Data</strong>
          </span>
        </li>
      </ul>
      <p class="p12">
        <br />
      </p>
      <p class="p8">
        We use cookies and similar tracking technologies to track the activity
        on our Service and hold certain information.
      </p>
      <p class="p8">
        Cookies are files with small amount of data which may include an
        anonymous unique identifier. Cookies are sent to your browser from a
        website and stored on your device. Tracking technologies also used are
        beacons, tags, and scripts to collect and track information and to
        improve and analyze our Service.
      </p>
      <p class="p8">
        You can instruct your browser to refuse all cookies or to indicate when
        a cookie is being sent. However, if you do not accept cookies, you may
        not be able to use some portions of our Service.
      </p>
      <p class="p13">
        <br />
      </p>
      <p class="p5">
        <strong>How do we use the information we collect?</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p3">
        Any of the information we collect from you may be used in one of the
        following ways:
      </p>
      <ul class="ul1">
        <li class="li7">
          <span class="s2">
            To personalize your experience (your information helps us to better
            respond to your individual needs)
          </span>
        </li>
        <li class="li7">
          <span class="s2">
            To improve our Service (we continually strive to improve our
            application offerings based on the information and feedback we
            receive from you)
          </span>
        </li>
        <li class="li7">
          <span class="s2">
            To improve customer service (your information helps us to more
            effectively respond to your customer service requests and support
            needs)
          </span>
        </li>
        <li class="li7">
          <span class="s2">To process transactions</span>
        </li>
        <li class="li7">
          <span class="s2">
            To administer a contest, promotion, survey or other site feature
          </span>
        </li>
        <li class="li7">
          <span class="s2">To send periodic emails</span>
        </li>
        <li class="li6">
          <span class="s2">To notify you about changes to our Service</span>
        </li>
        <li class="li6">
          <span class="s2">
            To gather analysis or valuable information so that we can improve
            our Service
          </span>
        </li>
        <li class="li6">
          <span class="s2">To monitor the usage of our Service</span>
        </li>
        <li class="li6">
          <span class="s2">
            To detect, prevent and address technical issues
          </span>
        </li>
        <li class="li6">
          <span class="s2">
            To provide you with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information
          </span>
        </li>
      </ul>
      <p class="p12">
        <br />
      </p>
      <p class="p10">
        <strong>How do we use your email address?</strong>
      </p>
      <p class="p9">
        <br />
      </p>
      <p class="p3">
        By submitting your email address, you agree to receive emails from us.
        You can cancel your participation in any of these email lists at any
        time by clicking on the opt-out link or other unsubscribe option that is
        included in the respective email. However, transactional emails are
        essential part of email-system and to stop receiving them, you must
        cancel the service completely.
      </p>
      <p class="p14">
        <br />
      </p>
      <p class="p3">
        We only send emails to people who have authorized us to contact them,
        either directly, or through a third party. We do not send unsolicited
        commercial emails, because we hate spam as much as you do.
        <span class="Apple-converted-space">&nbsp;</span>
      </p>
      <p class="p7">
        <span class="s2">
          Email addresses submitted only through the order processing page will
          be used for the sole purpose of sending you information and updates
          pertaining to your order. If, however, you have provided the same
          email to us through another method, we may use it for any of the
          purposes stated in this Policy. Note: If at any time you would like to
          unsubscribe from receiving future emails, we include detailed
          unsubscribe instructions at the bottom of each email.
        </span>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p5">
        <strong>How long do we keep your information?</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p8">
        We will retain your Personal Data for a period of five (5) years. We
        will retain and use your Personal Data to the extent necessary to comply
        with our legal obligations (for example, if we are required to retain
        your data to comply with applicable laws), resolve disputes, and enforce
        our legal agreements and policies.
      </p>
      <p class="p8">
        We will also retain Usage Data for internal analysis purposes. Usage
        Data is generally retained for a shorter period of time, except when
        this data is used to strengthen the security or to improve the
        functionality of our Service, or we are legally obligated to retain this
        data for longer time periods.
      </p>
      <p class="p7">
        We will retain the information we collect from you for a period of five
        (5) years, or until you are an active user of the services we provide.
        After the expiry of this period, we undertake to delete any information
        we have collected from you.
      </p>
      <p class="p13">
        <br />
      </p>
      <p class="p15">
        <strong>Disclosure of data</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <ul class="ul1">
        <li class="li6">
          <span class="s2">
            <strong>Business Transaction.</strong> If we are involved in a
            merger, acquisition or asset sale, your Personal Data may be
            transferred. We will provide notice before your Personal Data is
            transferred and becomes subject to a different Privacy Policy.
          </span>
        </li>
        <li class="li6">
          <span class="s2">
            <strong>Disclosure for Law Enforcement.</strong> Under certain
            circumstances, we may be required to disclose your Personal Data if
            required to do so by law or in response to valid requests by public
            authorities (e.g., a court or a government agency).
          </span>
        </li>
      </ul>
      <p class="p13">
        <br />
      </p>
      <p class="p5">
        <strong>How do we protect your information?</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p3">
        We implement a variety of security measures to maintain the safety of
        your personal information when you place an order or enter, submit, or
        access your personal information. We offer the use of a secure server.
        All supplied sensitive/credit information is transmitted via Secure
        Socket Layer (SSL) technology and then encrypted into our Payment
        gateway providers&apos; database only to be accessible by those
        authorized with special access rights to such systems, and are required
        to keep the information confidential.
      </p>
      <p class="p14">
        <br />
      </p>
      <p class="p7">
        <span class="s2">
          After a transaction, your private information (credit cards, social
          security numbers, financials, etc.) is never kept on file. We cannot,
          however, ensure or warrant the absolute security of any information
          you transmit to 10goTech or guarantee that your information on the
          Service may not be accessed, disclosed, altered, or destroyed by a
          breach of our physical, technical, or managerial safeguards.
        </span>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p5">
        <strong>Your consent</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p7">
        By using our Software System/App, registering an account, accessing our
        services or products, you consent to this Privacy Policy Term.
      </p>
      <p class="p13">
        <br />
      </p>
      <p class="p5">
        <strong>Links to other websites</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p7">
        <span class="s2">
          This Privacy Policy applies only to our Services.&nbsp;
        </span>
        10goTech
        <span class="s2">
          &nbsp;may contain links to other websites not operated or controlled
          by our company. We are not responsible for the content, accuracy or
          opinions expressed in such websites, and such websites are not
          investigated, monitored or checked for accuracy or completeness by us.
          Please remember that when you use a link to go from the Services to
          another website, our Privacy Policy is no longer in effect. You are
          browsing and interaction on any other website, including those that
          have a link on our platform, is subject to that website&rsquo;s own
          rules and policies. Such third parties may use their own cookies or
          other methods to collect information about you.
        </span>
      </p>
      <p class="p9">
        <br />
      </p>
      <p class="p5">
        <strong>Information we collect and receive</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p7">
        We receive and store some information you knowingly provide to us. For
        example, through the registration process and/or through your account
        settings, we may collect Personal Information such as your name, email
        address and third-party account credentials (for example, your log-in
        credentials for Google, Apple or other third-party sites). If you
        provide your third-party account credentials to us, you understand some
        content and/or information in those accounts (&ldquo;Third-party Account
        Information&rdquo;) may be transmitted into your account with us if you
        authorise such transmissions, and that Third Party Account Information
        transmitted to our Services is covered by this Privacy Policy; for
        example, if you connect with us through Google or Apple, some of your
        user information from those sites may be transferred as well (though you
        may be able to edit them later). Certain information may be required to
        register with us or to take advantage of some of our features.
      </p>
      <p class="p7">
        We may communicate with you if you&rsquo;ve provided us the means to do
        so. For example, if you&rsquo;ve given us your email address, we may
        send you promotional email offers on behalf of other businesses, or
        email you about your use of the Services. If you do not want to receive
        communications from us, please indicate your preference by emailing us
        at support@10goTech.co.uk
      </p>
      <p class="p4">
        <span class="Apple-converted-space">&nbsp;</span>
      </p>
      <p class="p5">
        <strong>Information collected automatically</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p7">
        Whenever you interact with our Services, we automatically receive and
        record information on our server logs from your browser or device, which
        may include your IP address, geolocation data, device identification,
        &ldquo;cookie&rdquo; information, the type of browser and/or device
        you&rsquo;re using to access our Services, and the page{" "}
        <span class="s5">or</span> feature you requested. &ldquo;Cookies&rdquo;
        are identifiers we transfer to your browser or device that allow us to
        recognize your browser or device and tell us how and when pages and
        features in our Services are visited and by how many people. You may be
        able to change the preferences on your browser or device to prevent or
        limit your device&rsquo;s acceptance of cookies, but this may prevent
        you from taking advantage of some of our features. Our advertising
        partners may also transmit cookies to your browser or device, when you
        click on ads that appear on the Services. Also, if you click on a link
        to a third-party website or service, such third party may also transmit
        cookies to you. Again, this Privacy Policy does not cover the use of
        cookies by any third parties, and we aren&rsquo;t responsible for their
        privacy policies and practices. Please be aware that cookies placed by
        third-parties may continue to track your activities online even after
        you have left our Services, and those third-parties may not honor
        &ldquo;Do Not Track&rdquo; requests you have set using your browser or
        device.
      </p>
      <p class="p7">
        We may use this data to customize content for you that we think you
        might like, based on your usage patterns. We may also use it to improve
        the Services&mdash;for example, this data can tell us how often users
        use a particular feature of the Services, and we can use that knowledge
        to make the Services interesting to as many users as possible.
      </p>
      <p class="p13">
        <br />
      </p>
      <p class="p5">
        <strong>Security of Your Information</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p7">
        Your account is protected by a password for your privacy and security.
        You must prevent unauthorised access to your account and Personal
        Information by selecting and protecting your password appropriately and
        limiting access to your computer or device and browser by signing off
        after you have finished accessing your account.
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p7">
        We endeavor to protect the privacy of your account and other Personal
        Information we hold in our records, but unfortunately, we cannot
        guarantee complete security. Unauthorized entry or use, hardware or
        software failure, and other factors, may compromise the security of user
        information at any time.
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p5">
        <strong>Information retention and deletion</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p7">
        Through your account settings, you may access, and, in some cases, edit
        or delete the following information you&rsquo;ve provided to us:
      </p>
      <p class="p16">
        &nbsp;
        <br />- name
        <br />- password
        <br />- email address
        <br />- credit card information
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p7">
        The information you can view, update, and delete may change as the
        Services change. If you have any questions about viewing or updating
        information, we have on file about you. Please contact us at{" "}
        <a href="mailto:rob@10gotech.com">
          <span class="s6">rob@10gotech.com</span>
        </a>
      </p>
      <p class="p4">
        <span class="Apple-converted-space">&nbsp;</span>
      </p>
      <p class="p5">
        <strong>Your choices</strong>
      </p>
      <p class="p13">
        <br />
      </p>
      <p class="p7">
        You can always opt not to disclose information to us, but keep in mind
        some information may be needed to register with us or to take advantage
        of some of our features.
      </p>
      <p class="p7">
        You may be able to add, update, or delete information as explained
        above. We may use any aggregated data derived from or incorporating your
        Personal Information after you update or delete it, but not in a manner
        that would identify you personally.
      </p>
      <p class="p17">
        <br />
      </p>
      <p class="p18">
        <strong>Legal Basis for Processing your Data</strong>
      </p>
      <p class="p19">
        10goTech legal basis for collecting and using the personal information
        described in this Platform Agreement depends on the Personal Data we
        collect and the specific context in which we collect it.
      </p>
      <p class="p19">10goTech may process your Personal Data because:</p>
      <ul class="ul1">
        <li class="li20">
          <span class="s2">We need to perform a contract with you;</span>
        </li>
        <li class="li20">
          <span class="s2">You have given us permission to do so;</span>
        </li>
        <li class="li20">
          <span class="s2">
            The processing is in our legitimate interests, and it&apos;s not
            overridden by your rights;
          </span>
        </li>
        <li class="li20">
          <span class="s2">For payment processing purposes;</span>
        </li>
        <li class="li20">
          <span class="s2">To comply with the law.</span>
        </li>
      </ul>
      <p class="p18">
        <strong>
          Data Protection Rights Under GDPRs / CCPA / PIPEDA / LGPD/ PDPA
        </strong>
      </p>
      <p class="p19">
        You have certain data protection rights. 10goTech aims to take
        reasonable steps to allow you to correct, amend, delete, or limit the
        use of your Personal Data.
      </p>
      <p class="p19">
        If you wish to be informed what Personal Data, we hold about you and if
        you want it to be removed from our systems, please contact us.
      </p>
      <p class="p19">
        In certain circumstances, you have the following data protection rights:
      </p>
      <ul class="ul1">
        <li class="li20">
          <span class="s2">
            The right to access, update, or to delete&nbsp;the information we
            have on you.
          </span>
        </li>
        <li class="li20">
          <span class="s2">
            The right of rectification.&nbsp;You have the right to have your
            information rectified if that information is inaccurate or
            incomplete.
          </span>
        </li>
        <li class="li20">
          <span class="s2">
            The right to object.&nbsp;You have the right to object to our
            processing of your Personal Data.
          </span>
        </li>
        <li class="li20">
          <span class="s2">
            The right of restriction.&nbsp;You have the right to request that we
            restrict the processing of your personal information.
          </span>
        </li>
        <li class="li20">
          <span class="s2">
            The right to data portability.&nbsp;You have the right to be
            provided with a copy of your Personal Data in a structured,
            machine-readable and commonly used format.
          </span>
        </li>
        <li class="li20">
          <span class="s2">
            The right to withdraw consent.&nbsp;You also have the right to
            withdraw your consent at any time where the 10goTech relied on your
            consent to process your personal information.
          </span>
        </li>
      </ul>
      <p class="p3">
        Please note that we may ask you to verify your identity before
        responding to such requests.
      </p>
      <p class="p3">
        You have the right to complain to a Data Protection Authority about our
        collection and use of your Personal Data. For more information, please
        contact your local data protection authority in your country.
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p3">
        <span class="s5">
          <strong>Governing Law:&nbsp;</strong>
        </span>
        This Agreement shall be governed by the laws of Delaware. The parties
        agree that the exclusive jurisdiction of any dispute arising from this
        Contract shall be heard and determined by the competent jurisdiction of
        the courts in Delaware.<span class="Apple-converted-space">&nbsp;</span>
      </p>
      <p class="p9">
        <br />
      </p>
      <p class="p10">
        <strong>Data Protection Officer</strong>
      </p>
      <p class="p3">
        We have appointed a Data Protection Officer (&ldquo;DPO&rdquo;) who is
        responsible for overseeing questions about this privacy notice. If you
        have any questions about this privacy notice, including any requests to
        exercise your legal rights, please contacts Data Protection Officer, at
        rob@10gotech.com
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p5">
        <strong>Changes to this Privacy Policy</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p8">
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on the Platform.
      </p>
      <p class="p8">
        We will let you know via email and/or a prominent notice on our Service,
        prior to the change becoming effective and update the &quot;effective
        date&quot; at the top of this Privacy Policy.
      </p>
      <p class="p8">
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
      <p class="p13">
        <br />
      </p>
      <p class="p5">
        <strong>Contact us</strong>
      </p>
      <p class="p4">
        <br />
      </p>
      <p class="p7">
        If you have any questions about this Privacy Policy, don&rsquo;t
        hesitate to contact us.
      </p>
      <p class="p21">
        <span class="s7">
          e-mail:{" "}
          <a href="mailto:rob@10gotech.com">
            <span class="s6">rob@10gotech.com</span>
            <span class="s8">
              <br />
              &nbsp;
              <br />
              &nbsp;
            </span>
          </a>
        </span>
      </p>
    </Layout>
  );
};

privacyPolicy.getInitialProps = async (context) => {
  console.log("requesting site...");
  const { data: site } = await buildClient(context).get(
    `/api/site/${context.query.site}`
  );

  console.log("request finished");

  return { privacyPolicy: site.privacyPolicy };
};

export default privacyPolicy;
