apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
        - name: site
          image: thesaas/site
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: rfp
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: site-srv
spec:
  selector:
    app: site
  ports:
    - name: site
      protocol: TCP
      port: 3000
      targetPort: 3000
