export const pp = `10GO TECH is committed to protecting your privacy. It governs the Privacy Terms of our Platform, located at https://www.10gotech.com This Privacy Policy explains how your personal information is collected, used, and disclosed by our Company.
By accessing or using our Service, you announce that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service. 

Definitions

Personal Data: Personal Data means data about a living individual who can be identified from those data. Personal Data is any information that directly, indirectly, or in connection with other information allows for the identification of a natural person. 
Usage Data: Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
Cookies: Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
Data Controller: Data Controller means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
Data Processors (or Service Providers): Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of Service Providers in order to process your data more effectively.
Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
Data Subject: Data Subject is any living individual who is the subject of Personal Data.
User: The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.

What Information Do We Collect?

We collect several types of information for various purposes to provide and improve our Service to you.

Types of Data Collected

Personal Data
While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (Personal Data). It means - Email address, first and last name, address, Country, Postcode, Phone number.

Usage Data

We may also collect information on how the Service is accessed and used (Usage Data). This Usage Data may include information such as your computer's Internet Protocol address (IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

Tracking & Cookies Data

We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.
Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.
You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.

How do we use the information we collect?

Any of the information we collect from you may be used in one of the following ways:
To personalize your experience (your information helps us to better respond to your individual needs)
To improve our Service (we continually strive to improve our application offerings based on the information and feedback we receive from you)
To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)
To process transactions
To administer a contest, promotion, survey or other site feature
To send periodic emails
To notify you about changes to our Service
To gather analysis or valuable information so that we can improve our Service
To monitor the usage of our Service
To detect, prevent and address technical issues
To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information

How do we use your email address?

By submitting your email address, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. However, transactional emails are essential part of email-system and to stop receiving them, you must cancel the service completely.

We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. 
Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.



How long do we keep your information?

We will retain your Personal Data for a period of five (5) years. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
We will retain the information we collect from you for a period of five (5) years, or until you are an active user of the services we provide. After the expiry of this period, we undertake to delete any information we have collected from you.

Disclosure of data

Business Transaction. If we are involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.
Disclosure for Law Enforcement. Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).

How do we protect your information?

We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers' database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential.

After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to 10GO TECH or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of our physical, technical, or managerial safeguards.

Your consent

By using our Software System/App, registering an account, accessing our services or products, you consent to this Privacy Policy Term.

Links to other websites

This Privacy Policy applies only to our Services. 10GO TECH may contain links to other websites not operated or controlled by our company. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. You are browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.

Information we collect and receive

We receive and store some information you knowingly provide to us. For example, through the registration process and/or through your account settings, we may collect Personal Information such as your name, email address and third-party account credentials (for example, your log-in credentials for Google, Apple or other third-party sites). If you provide your third-party account credentials to us, you understand some content and/or information in those accounts (“Third-party Account Information”) may be transmitted into your account with us if you authorise such transmissions, and that Third Party Account Information transmitted to our Services is covered by this Privacy Policy; for example, if you connect with us through Google or Apple, some of your user information from those sites may be transferred as well (though you may be able to edit them later). Certain information may be required to register with us or to take advantage of some of our features.
We may communicate with you if you’ve provided us the means to do so. For example, if you’ve given us your email address, we may send you promotional email offers on behalf of other businesses, or email you about your use of the Services. If you do not want to receive communications from us, please indicate your preference by emailing us at support@10GO TECH.co.uk
 
Information collected automatically

Whenever you interact with our Services, we automatically receive and record information on our server logs from your browser or device, which may include your IP address, geolocation data, device identification, “cookie” information, the type of browser and/or device you’re using to access our Services, and the page or feature you requested. “Cookies” are identifiers we transfer to your browser or device that allow us to recognize your browser or device and tell us how and when pages and features in our Services are visited and by how many people. You may be able to change the preferences on your browser or device to prevent or limit your device’s acceptance of cookies, but this may prevent you from taking advantage of some of our features. Our advertising partners may also transmit cookies to your browser or device, when you click on ads that appear on the Services. Also, if you click on a link to a third-party website or service, such third party may also transmit cookies to you. Again, this Privacy Policy does not cover the use of cookies by any third parties, and we aren’t responsible for their privacy policies and practices. Please be aware that cookies placed by third-parties may continue to track your activities online even after you have left our Services, and those third-parties may not honor “Do Not Track” requests you have set using your browser or device.
We may use this data to customize content for you that we think you might like, based on your usage patterns. We may also use it to improve the Services—for example, this data can tell us how often users use a particular feature of the Services, and we can use that knowledge to make the Services interesting to as many users as possible.

Security of Your Information

Your account is protected by a password for your privacy and security. You must prevent unauthorised access to your account and Personal Information by selecting and protecting your password appropriately and limiting access to your computer or device and browser by signing off after you have finished accessing your account.

We endeavor to protect the privacy of your account and other Personal Information we hold in our records, but unfortunately, we cannot guarantee complete security. Unauthorized entry or use, hardware or software failure, and other factors, may compromise the security of user information at any time.

Information retention and deletion

Through your account settings, you may access, and, in some cases, edit or delete the following information you’ve provided to us:
 - name - password - email address - credit card information

The information you can view, update, and delete may change as the Services change. If you have any questions about viewing or updating information, we have on file about you. Please contact us at rob@10gotech.com
 
Your choices

You can always opt not to disclose information to us, but keep in mind some information may be needed to register with us or to take advantage of some of our features.
You may be able to add, update, or delete information as explained above. We may use any aggregated data derived from or incorporating your Personal Information after you update or delete it, but not in a manner that would identify you personally.

Legal Basis for Processing your Data
10GO TECH legal basis for collecting and using the personal information described in this Platform Agreement depends on the Personal Data we collect and the specific context in which we collect it.
10GO TECH may process your Personal Data because:
We need to perform a contract with you;
You have given us permission to do so;
The processing is in our legitimate interests, and it's not overridden by your rights;
For payment processing purposes;
To comply with the law.
Data Protection Rights Under GDPRs / CCPA / PIPEDA / LGPD/ PDPA
You have certain data protection rights. 10GO TECH aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
If you wish to be informed what Personal Data, we hold about you and if you want it to be removed from our systems, please contact us.
In certain circumstances, you have the following data protection rights:
The right to access, update, or to delete the information we have on you.
The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.
The right to object. You have the right to object to our processing of your Personal Data.
The right of restriction. You have the right to request that we restrict the processing of your personal information.
The right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format.
The right to withdraw consent. You also have the right to withdraw your consent at any time where the 10GO TECH relied on your consent to process your personal information.
Please note that we may ask you to verify your identity before responding to such requests.
You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in your country.

Governing Law: This Agreement shall be governed by the laws of Delaware. The parties agree that the exclusive jurisdiction of any dispute arising from this Contract shall be heard and determined by the competent jurisdiction of the courts in Delaware. 

Data Protection Officer
We have appointed a Data Protection Officer (“DPO”) who is responsible for overseeing questions about this privacy notice. If you have any questions about this privacy notice, including any requests to exercise your legal rights, please contacts Data Protection Officer, at rob@10gotech.com

Changes to this Privacy Policy

We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on the Platform.
We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.
You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

Contact us

If you have any questions about this Privacy Policy, don’t hesitate to contact us.
e-mail: rob@10gotech.com
`;

export const ua = `
10GO TECH LLC doing business as 10GO TECH (“we or “10GO TECH” or “Company”) provides Digital products & consulting (“web-application” or “System”) for use by you (“User”). 

By accessing, downloading, and/or using 10GO TECH and/or the Services, you agree to this User Agreement (“Agreement”). THESE USER TERMS CREATE A BINDING LEGAL AGREEMENT BETWEEN YOU AND 10GO TECH, 10GO TECH and customers of 10GO TECH PLEASE READ THEM CAREFULLY. IF YOU DO NOT AGREE WITH ANY OF THESE TERMS, YOU SHOULD NOT ACCESS, DOWNLOAD, and/or use our website/service/app.

10GO TECH reserves the right to modify these Terms at any time by email or posting a notice on the Platform. Your access to the Platform after the notice is posted indicates acceptance of those changes.

Definitions

When the following words are used in these Terms, this is what they will mean:

Company: When this terms mention “Company,” “we,” “us,” or “our,” it refers to 10GO TECH that is responsible for the information under this Agreement.
Software: The online software applications provided by 10GO TECH as part of the Services.
User: Means the customer, person, company, or organisation who purchases Subscription Service from 10GO TECH Platform.
License Fee: The subscription licence fee payable by the User to 10GO TECH as set out in this Agreement.
Intellectual Property Rights: Means (without limitation) any patents, rights to inventions, copyright and related rights, trade-marks and service marks, goodwill and the right to sue for passing off, rights in designs, rights in computer software, database rights, rights to use, in each case whether registered or unregistered and including all applications and rights to apply for and be granted, renewals or extensions of, and rights to claim priority from, such rights and all similar or equivalent rights or forms of protection which subsist or will subsist now or in the future in any part of the world.
Notification: The email/push sent from 10GO TECH to a User.
Website: https://10gotech.com

General Restrictions

You represent, warrant, and agree that you will not use the Website, interact with the Services, in a manner that:

(a) Infringes or violates the intellectual property rights or any other rights of anyone else (including 10GO TECH);
(b) Violates any law, international law, including, without limitation, any applicable export control laws;
(c) Is harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable;
(d) Jeopardizes the security of your 10GO TECH account or anyone else’s (such as allowing someone else to log in to the Services as you);
(e) Attempts, in any manner, to obtain the password, account, or other security information from any other user;
(f) Violates the security of any computer network, or cracks any passwords or security encryption codes;
(g) Runs Mail list, Listserv, any form of auto-responder or “spam” on the Services, or any processes that run or are activated while you are not logged into the Services, or that otherwise interfere with the proper working of the Services (including by placing an unreasonable load on the Services’ infrastructure);
(h) “Crawls,” “scrapes,” or “spiders” any page, data, or portion of or relating to the Services or Content (through use of manual or automated means);
(i) Copies or stores any significant portion of the Content; or
(j) Decompiles, reverse engineers, or otherwise attempts to obtain the source code or underlying ideas or information of or relating to the Services.

A VIOLATION OF THE FOREGOING IS GROUNDS FOR TERMINATION OF YOUR RIGHT TO USE OR ACCESS THE SERVICES.

License & Delivery

3.1 License
10GO TECH hereby grants You a nonexclusive, nontransferable license to use 10GO TECH Software for Customer’s internal business purposes on your device, solely as a component of the System provided You comply with the restrictions set forth below in Section 3.2 (Restrictions on Software Rights). The license in the preceding sentence does not include use by any third party, and You shall not permit any such use. 

3.2 Restrictions on Software Rights
	
In consideration You acknowledge that all Intellectual Property Rights in the Software System anywhere in the world belong to 10GO TECH or its licensors, that rights in the Software are licensed (not sold) to you, and that you have no rights in, or to, the Software, other than the right to use it in accordance with these Terms. You acknowledge that you have no right to have access to the System in source-code form.

Without limiting the generality of the foregoing, User shall not: (a) modify, create derivative works from, distribute, publicly display, publicly perform, or sublicense the software; (b) use the Software for service bureau or time-sharing purposes or in any other way allow third parties to exploit the software; or (c) reverse engineer, decompile, disassemble, or otherwise attempt to derive any of the Software’s source code.

Confidential Information

Confidential Information refers to the following one party to this Agreement (Discloser) discloses to the other (Recipient): (a) any document Discloser marks confidential; (b) any information Discloser orally designates as “Confidential” at the time of disclosure; (c) the nonpublic features and functions of the Software, for which 10GO TECH is Discloser; and (d) any other nonpublic, sensitive information Recipient should reasonably consider a trade secret or otherwise confidential. Notwithstanding the foregoing, Confidential Information does not include information that: (i) is in Recipient’s possession at the time of disclosure; (ii) becomes know publicly, before or after disclosure, other than as a result of Recipient’s improper action or inaction; or (iv) is approved for release in writing by Discloser. Recipient is on notice that the Confidential information may include Discloser’s valuable trade secrets. 

4.1 Nondisclosure

Recipient shall not use Confidential Information for any purpose other than to facilitate the transactions contemplated by this Agreement (the “Purpose”). Recipient: (a) shall not disclose Confidential Information to any employee or contractor or Recipient unless such person needs access in order to facilitate the Purpose and executes a nondisclosure agreement with Recipient with terms no less restrictive that those of this Article 4; and (b) shall not disclose Confidential Information to any other third party without Discloser’s prior written consent. Without limiting the generality of the foregoing, Recipient shall protect Confidential Information with the same degree of care it uses to protect its own confidential information of similar nature and importance, but with no less than reasonable care. Recipient shall promptly notify Discloser of and misuse or misappropriation of confidential Information that comes to Recipient’s attention. Notwithstanding the foregoing, Recipient may disclose Confidential Information as required by applicable law or by proper legal or governmental authority. Recipient shall give Discloser prompt notice of any such legal or governmental demand and reasonably cooperate with Discloser in any effort to seek a protective order or otherwise to contest such required disclosure, at Discloser’s expense.

4.2 Injunction

Recipient agrees that breach of this Article 4 would cause Discloser irreparable injury, for which monetary damages would not provide adequate compensation, and that in addition to any other remedy, Discloser will be entitled to injunctive relief against such breach or threatened breach, without proving actual damage or posting a bond or other security. 

Property Rights

As between You and 10GO TECH, we own or license all data, content, graphics, audio clips, video clips, presentations, forms, artwork, images, photographs, functional components, and any software concepts and documentation and other material on, in, or made available through the Products, as well as the selection, coordination, arrangement, organization, and enhancement of the Product Materials. All Product Materials are protected pursuant to copyright, trademark, patent, and other applicable laws. As between any User and 10GO TECH, all names, trademarks, service marks, certification marks, symbols, slogans, or logos (“Trademarks”) appearing on the Products are proprietary to 10GO TECH or its affiliates, licensors, or suppliers. Use or misuse of these Trademarks is expressly prohibited and may violate federal trademark law. Unless expressly written otherwise by 10GO TECH, You have the right to use the Product Materials in accordance with these Terms.

Subscription Terms

Your subscription begins as soon as your initial payment is processed. Your subscription will automatically renew each month without notice until you cancel. You authorise us to store your payment method(s) and to automatically charge your payment method(s) every month until you cancel. We will automatically charge you the then-current rate for your plan, plus applicable taxes, every month upon renewal until you cancel.

If your primary payment method fails, you authorise us to charge any other payment method in your account. If you have not provided us a backup payment method(s) and you fail to provide payment, or if all payment methods in your account fail, we may suspend your subscription. 

Cancellation Terms

You can cancel your subscription anytime via your 10GO TECH account page. 
Or the Agreement is otherwise terminated in accordance with its Terms, (and any Trial Period and Subscription Term(s) shall together constitute the “Term”).
Should you cancel after Trial Period, your payment in nonrefundable, and your service will be stopped immediately.

Acceptable Use

You shall not 
(a) provide System passwords or other log-in information to any third-party; 
(b) share nonpublic System features or content with any third-party; 
(c) access the System in order to build a competitive product or service, to build a product using similar ideas, features, functions or graphics of the System, or to copy any ideas; or 
(d) engage in web scraping or data scraping on or related to the System, including without limitation collection of information through any software that simulates human activity or any bot or web crawler. 

If 10GO TECH suspects that you have violated the requirements of this section, we may suspend your access to the System without advanced notice, in addition to other remedies we may have. 

10GO TECH is not obligated to take any action against you or any other System user or other third party for violating this Agreement, but we are free to take any such action it sees fit.

System Access

You are responsible and liable for: 
(a) your use of the System, including unauthorised conduct and conduct that would violate the requirements of this Agreement; 
(b) any use of the System through your account or passwords, whether authorized or not.

Unauthorized Access

You agree to take reasonable steps to prevent unauthorized access to the System, including by protecting your password and other log-in information. You shall notify 10GO TECH immediately if you know of or suspect unauthorized use of the System or breach of its security. 

Compliance with Law

In using the Platform, you shall comply with all applicable laws, including laws governing the protection of personally identifiable information and other laws applicable to the protection of your content.

Right to Retain, Delete, or Suspend Access

You agree that you shall not rely on the System for backup or storage or your content. 10GO TECH may retain your content even if you are no longer using the System but is not required to provide copies of your content to you. 10GO TECH may permanently delete or erase your content or suspend your access to your content through the System at any time and for any reason.

Disclaimer of Liability

10GO TECH is not liable, and you agree not to hold us (owners, founder, co-founders, executive team, employees, subsidiaries, affiliates, agents) responsible for any: DAMAGES FOR LOSS OF REVENUES, PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES ARISING OUT OF OR RELATED TO YOUR USE OF THE SITE OR THE SERVICES, REGARDLESS OF WHETHER SUCH DAMAGES ARE BASED ON CONTRACT, TORT (INCLUDING NEGLIGENCE AND STRICT LIABILITY), WARRANTY, STATUTE OR OTHERWISE.

Disclaimer of Warranties

10GO TECH disclaims all warranties, express or implied regard to this service. 10GO TECH does not make representations of any kind or warranties available to you through the Platform.  
No oral advice or written information given by 10GO TECH or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty.
WITHOUT LIMITATING THE GENERALITY OF THE FOREGOING: (a) 10GO TECH HAS NO OBLIGATION TO INDEMNIFY OR DEFEND YOU AGAINST CLAIMS RELATED TO INFRINGMENT OF INTELLECTUAL PROPERTY; (b) 10GO TECH DOES NOT REPRESENT OR WARRANT THAT THE SYSTEM WILL PREFORM WITHOUT INTERRUPTION OR ERROR; (c) 10GO TECH DOES NOT REPRESENT OR WARRANT THAT THE SYSTEM IS SECURE FROM HACKING OR OTHER UNAUTHORIZED INTRUSION OR THAT YOUR CONTENT WILL REMAIN PRIVATE OR SECURE; AND (d) 10GO TECH DISCLAIMS ANY REPRESENTATION OR WARRANTY CONCERNING PRODUCTS OR SERVICES PROVIDED BY OTHER USERS OF THE SYSTEM OR OTHER THIRD PARTIES. 

Risk of Exposure

You understand and agree that sharing content online involves risks of unauthorized disclosure or exposure and that, in submitting your content, data to or transmitting it through the system, you assume the risks. 10GO TECH offers no representation, warranty, or guarantee that your content will not be exposed or disclosed through the System or through errors or the actions of third parties.

The Risks exist and are really dangerous in the online environment. It is important to be aware of the risks that subsist on the internet and how to minimize them:

Exposure to inappropriate material
Illegal activities
Harassment
Legal and financial risks
Identity theft
Cyberattack
Invasion of privacy
Data breach
Scams

 Cybersecurity and Online Platform Disclaimer

Cyber Security is technologies, processes, procedures and controls that are designed to protect Digital Environments from Cyber Security Incidents;
Cyber Security Incident is the loss or unauthorised destruction, alteration, disclosure of, access to, or control of a Digital Environment;
Digital Environment is information technology systems, operational technology systems, networks, internet-enabled applications or devices and the data contained within such systems.

10GO TECH has implemented administrative, physical and technical safeguards to protect Client’s Personal information. We shall ensure that all such safeguards, including the manner in which Personal Information is collected, accessed, used, stored, processed, disposed of and disclosed, comply with applicable data protection and privacy laws, as well as the terms and conditions of this Agreement.
 
You understand and agree that sharing content online involves risks of unauthorised disclosure or exposure and that, in submitting your content to or transmitting it through the system, you assume the risks. 10GO TECH offers no representation, warranty, or guarantee that your content will not be exposed or disclosed through the System or through errors or the actions of third parties.

10GO TECH is not liable, and you agree not to hold us responsible for any damages or losses arising out of or in connection with this Agreement, including, but not limited to:

Your use of or your inability to use our Site or Site Services;
Delays or disruptions in our Site or Site Services;
Viruses or other malicious software got by accessing, or linking to, our Site or Site Services;
Glitches, bugs, errors, or inaccuracies of any kind in our Site or Site Services;
Damage to your hardware device from the use of the Site or Site Services;
The content, actions, or inactions of third parties’ use of the Site or Site Services;
A suspension or other action taken regarding your Account;

Information Security Experts

Regularly we consult with our developers if urgent issues arise with the site or if there is scheduled feature releases or upgrades.
Hosting company will only be asked to access the data in the site's event being down or server issues.
We may consult with security experts to ensure continuous site safety and compliance.

Cyberattack Disclaimer

A cyberattack is where an attacker tries to gain unauthorized access to an IT system for the purpose of theft, extortion, disruption on other nefarious reasons.
Normally, a cyberattack is carried out by someone who is not, or was not, a member of your organization.

10GO TECH strives to protect Customers against Cyberattacks. We have implemented our system with security experts; we take different types of security measures, but the Internet environment is a 24/7 risky and vulnerable.

We are not liable for any Cyberattack, damage, or loss on the World Wide Web. You expressly agree and acknowledge that the use of the 10GO TECH Platform is at your sole risk. In no event will 10GO TECH, 10GO TECH professionals or their officers, employees, directors, parents, subsidiaries, affiliates, agents or licensors be liable for any indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of revenues, profits, goodwill, use data or other intangible losses arising out of or related to your use of the site or the services.

Types of Cyberattacks we take no responsibility:

Malware: is a type of application that can perform a variety of malicious tasks – spy on the user in other to obtain credentials or other valuable data or to cause disruption.

Phishing: is where the attacker tries to trick an unsuspecting victim into handing over valuable information, such as passwords, credit card details, intellectual property, and so on.

MITM - Man-in-the-middle-attack is where an attacker intercepts the communications between two parties in an attempt to spy on the victims, steal personal information or credentials, or perhaps alter the conversation in some way. 

DDoS – Distributed Denial-of-Service attack – is where an attacker essentially floods a target server with traffic in an attempt to disrupt, and perhaps even bring down the target. A DDoS attack is able to leverage multiple compromised devices to bombard the target with traffic.

SQL injection: is a type of attack which is specific to SQL databases. The attacker can exploit the HTML form to execute queries that will create, read, modify, or delete the data stored in the database.

Zero-day exploit: is where cyber-criminals learn of a vulnerability that has been discovered in certain widely-used software applications and operation systems, and then target organizations who are using that software in order to exploit the vulnerability before a fix becomes available.

DNS tunnelling: is a sophisticated attack vector that is designed to provide attackers with persistent access to a given target. Attacker are able to insert or tunnel malware into DNS queries. The malware is used to create a persistent communication channel that most firewalls are unable to detect.

BEC – Business Email Compromise: is where the attacker targets specific individuals, usually an employee who has the ability to authorize financial transactions, in order to trick into transferring money into an account controlled by the attacker. BEC attacks usually involve planning and research in order to be effective.

Cryptojacking: is where cyber criminals compromise a user’s computer or device and use it to mine cryptocurrencies, such as Bitcoin. Organizations don’t have great visibility when it comes to this type of attack, which means that a hacker could use valuable network resources to mine a cryptocurrency without the organization having any knowledge of it. 

Drive-by Attack: A drive-by-download’ attack is where an unsuspecting victim visits a website which in turn infects their device with malware. The website in question could be one that is directly controlled by the attacker, or one that has been compromised. In some cases, the malware is served in content such as banners and advertisements.

Cross-site scripting (XSS) attacks: Cross-site scripting attacks are quite similar to SQL injection attacks, although instead of extracting data from a database, they are typically used to infect other users who visit the site. It can happen on the comment section on a webpage.

Password attack: is a type of cyberattack where an attacker tries to guess, or crack a user’s password. Some examples: Brute-force attack, Dictionary attack, Rainbow table attack, Credential stuffing, Password spraying and Keylogger attack.

Eavesdropping attack: Sometimes referred as “snooping” or “sniffing”, an eavesdropping attack is where the attacker looks for unsecured network communications to intercept and access data that is being sent across the network.

AI-Powered attack: AI-powered software is able to slave machines to perform a huge DDoS attack. Also, can learn what kinds of approaches work best and adapt their attack methods accordingly. They can use intelligence feeds to quickly identify software vulnerabilities, as well as scan systems themselves for potential vulnerabilities. AI-powered attacks can work around the clock, they are fast, efficient, affordable and adaptable.

IOT-Based attacks: is a type of attack where an attacker goes through an IOT (internet-of-things) device and exploit target such as medical devices, security systems, smart thermometers in order to launch large-scale DDoS attacks.



Cookies 

10GO TECH uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the content that you see on our website. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies. By using our site, registering an account, or making a purchase, you consent to the fact that we use cookies.

Privacy Policy 

You acknowledge the collection, use, disclosure and other handling of information described in our Privacy Policy https://www.10gotech.com/privacy-policy which we may update from time to time.

How we Protect your Data

We implement a variety of security measures to maintain the safety of your personal information when you use our service through the Platform. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers' database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. 

After a transaction, your private information (credit cards, social security numbers, financials, etc.,) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to 10GO TECH or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of our physical, technical, or managerial safeguards.

Legal Basis for Processing your Data

If you are from The United States, The United Kingdom or European Economic Area (EEA), 10GO TECH legal basis for collecting and using the personal information described in this Platform Agreement depends on the Personal Data we collect and the specific context in which we collect it.

10GO TECH may process your Personal Data because:
We need to perform a contract with you;
You have given us permission to do so;
The processing is in our legitimate interests, and it's not overridden by your rights;
For payment processing purposes;
To comply with the law.

Data Protection Rights Under GDPRs / CCPA / PIPEDA / LGPD/ PDPA

You have certain data protection rights. 10GO TECH aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
If you wish to be informed what Personal Data, we hold about you and if you want it to be removed from our systems, please contact us.

In certain circumstances, you have the following data protection rights:
The right to access, update, or to delete the information we have on you.
The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.
The right to object. You have the right to object to our processing of your Personal Data.
The right of restriction. You have the right to request that we restrict the processing of your personal information.
The right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format.
The right to withdraw consent. You also have the right to withdraw your consent at any time where the 10GO TECH relied on your consent to process your personal information.

Conduct and Behaviour

Without limiting other remedies, we may limit, suspend, or terminate your User account and access to our Services, restrict or prohibit access to, and your activities on, our Services, remove or demote, delay or remove hosted content, remove any special status associated with the account, reduce or eliminate any discounts, and take technical and legal steps to keep you from using our Services if:

we think that you are creating problems or possible legal liabilities for us, our users, suppliers or other third parties;
we think that such restrictions will improve the security of the 10GO TECH community or reduce our or another 10GO TECH user's exposure to financial liabilities;
we think that you are infringing the rights of third parties;
we think that you are acting inconsistently with the letter or spirit of this User Agreement or our policies or abuse our employees or users.

Indemnification

You agree to defend, indemnify, and hold harmless 10GO TECH and the 10GO TECH Associates, officers, directors, shareholders, parents, subsidiaries, agents, successors, and assigns, against any “Indemnify Claim”, meaning any third-party claim, suit, or proceeding arising out of, related to, or alleging: (a) infringement or violation of third party intellectual property, privacy or publicity rights by content submitted to or transmitted through the System from your account, including without limitation by your content; and (b) claims that use of the System through your account harasses, defames, or defrauds a third party, infringe, or misappropriates, copyright, trade secret, or other intellectual property rights, or violates the CAN-Spam Act Compliance or any other law or restriction on electronic advertising. 10GO TECH will have the right, not to be exercised unreasonably, to reject any settlement or compromise that requires that it admit wrongdoing or liability or subjects it to any ongoing affirmative obligations. 

In no event shall 10GO TECH, its employees, agents, and sub-contractors be liable to the Customer to the extent that the alleged infringement is based on:

A modification of the Services or Documentation by anyone other than 10GO TECH, unless approved in writing by 10GO TECH; or
A combination of the Software with software or products not supplied or approved in writing by 10GO TECH;
The Customer's use of the Services or Documentation in a manner contrary to the instructions given to the Customer by 10GO TECH; or
The Customer's use of the Services or Documentation after notice of the alleged or actual infringement from 10GO TECH or any appropriate authority.
    
 The Customer shall defend, indemnify and hold harmless 10GO TECH against claims, actions, proceedings, losses, damages, expenses, and costs (including without limitation court costs and reasonable legal fees) arising out of or in connection with the Customer's use of the Services and/or Documentation, provided that:

Any such claim does not arise as a result of any breach by 10GO TECH of its obligations under the Agreement;
The Customer is given prompt notice of any such claim;
10GO TECH provides reasonable co-operation to the Customer in the defence and settlement of such claim, at the Customer's expense; and
The Customer is given sole authority to defend or settle the claim.

Term &Termination

22.1 Term
The Term of this Agreement (the “Term”) will commence on the Effective Date and continue until terminated by either you or 10GO TECH.

22.2 Termination
Either party may terminate this Agreement for any reason at any time. You may terminate this Agreement by closing your account. 10GO TECH may terminate by notifying You in writing (including without limitation via text to your mobile device) and closing Your account.

Cause for such termination shall include, but not be limited to: (a) violations of these Terms of Use; (b) a request by you to cancel or terminate your account; (c) discontinuance or material modification to the Service or any part thereof; (d) a request and/or order of law enforcement, a judicial body, or other government agency; (e) provision of the 10GO TECH Services to you becoming unlawful; (f) unexpected technical or security issues or problems; or (g) your participation in fraudulent or illegal activities. Any such termination or suspension shall be made by us in our sole discretion, without any refund to you of any prepaid fees or amounts, and we will not be responsible to you or any third party for any damages that may result or arise out of such termination or suspension of your account and/or access to the 10GO TECH Services. 

22.3 Effects of Termination 
Upon termination of this Agreement, Customer shall cease all use of the Software. The following will survive termination or expiration of this Agreement: (a) any obligation of Customer to pay fees incurred before termination; (b) Articles and Sections 3.2 (Restrictions on Software Rights), 4 (Confidential Information), 4.1 (Nondisclosure), 5 (Property Rights), 13 (Disclaimer of Liability), 14 (Disclaimer of Warranties), 21 (Indemnification); and (c) any other provision of this Agreement that must survive to fulfill its essential purpose.

Miscellaneous

Governing Law: This Agreement shall be governed by the laws of Delaware. The parties agree that the exclusive jurisdiction of any dispute arising from this Contract shall be heard and determined by the competent jurisdiction of the courts in Delaware. 

Force Majeure: Neither party to these terms will be deemed liable for its failure to perform or delay in performance under these Terms where such delay or failure is beyond its control, such as were caused by internet or telecommunications failures, shortages of or inability to obtain labor, energy, or supplies, war, terrorism, riot, acts of God or governmental action, natural disasters. 

Severability: If any provision of this Agreement is determined to be illegal or unenforceable, such provision shall be automatically reformed and construed so as to be valid, operative and enforceable to the maximum extent permitted by law or equity while preserving its original intent. The invalidity of any part of this Agreement shall not render invalid the remainder of this Agreement.


Contact us
Please Contact us if you have any questions or concerns regarding this Agreement.
e-mail: rob@10gotech.com
`;
